init:
  - git config --global core.autocrlf true

branches:
  only:
    - appveyor
    - master

before_build:
  - '"%VS140COMNTOOLS%VsDevCmd.bat"'
  - BeforeBuild.cmd

platform: Any CPU

configuration:
#  - Debug
  - Release

build:
  project: src/Everything.sln
  
test:
  assemblies:
    - '**\Sarif.UnitTests.dll'
    - '**\Sarif.Driver.UnitTests.dll'
    - '**\Sarif.FunctionalTests.dll'
    - '**\Sarif.ValidationTests.dll'

notifications:
  - provider: Email
    to:
      - $env:EMAIL
      - $env:PERSONAL
    subject: 'Sarif-SDK Build {{status}}'
    message: "{{message}}, {{commitID}}"
    on_build_status_changed: true

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'
