init:
  - git config --global core.autocrlf true

branches:
  only:
    - master

before_build:
  - '"%VS140COMNTOOLS%VsDevCmd.bat"'
  - BeforeBuild.cmd

platform: Any CPU

configuration:
#  - Debug
  - Release

environment:
  _CL_: /analyze:autolog:extsarif
  _CSC_: /analyzer:'Microsoft.CodeAnalysis.Analyzers\*'

build:
  project: src/Everything.sln

after_build:
  - '"%VS140COMNTOOLS%VsDevCmd.bat"'
  - ConvertToSarif.cmd

before_test:
  - ps: Push-AppveyorArtifact prefastresult.sarif
  - ps: Push-AppveyorArtifact 'src\PREfastXmlSarifConverter\prefastresult.pftlog'
  - ps: .\jsonparse.ps1 "prefastresult.sarif" %APPVEYOR_REPO_PROVIDER% %APPVEYOR_REPO_NAME%; ls
  - ps: Push-AppveyorArtifact githubprefastresult.sarif
  
test:
  assemblies:
    - '**\Sarif.UnitTests.dll'
    - '**\Sarif.Driver.UnitTests.dll'
    - '**\Sarif.FunctionalTests.dll'
    - '**\Sarif.ValidationTests.dll'

notifications:
  - provider: Email
    to:
     - t-rools@microsoft.com
    subject: '{{projectName}} Build {{status}}: Version: {{buildVersion}}'
    on_build_status_changed: true

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'
