init:
  - git config --global core.autocrlf true

branches:
  only:
    - master

before_build:
  - '"%VS140COMNTOOLS%VsDevCmd.bat"'
  - BeforeBuild.cmd

platform: Any CPU

configuration:
#  - Debug
  - Release

build:
  project: src/Everything.sln
  
test:
  assemblies:
    - '**\Sarif.UnitTests.dll'
    - '**\Sarif.Driver.UnitTests.dll'
    - '**\Sarif.FunctionalTests.dll'
    - '**\Sarif.ValidationTests.dll'
    
artifacts:
  - path: 'bld\bin'

notifications:
  - provider: Email
    to:
      - vsarcplat@microsoft.com
    subject: 'Sarif-SDK Build {{status}}'
    message: 'In reference to {{commitID}}. View output <a href="{{buildURL}}">here</a> '
    on_build_status_changed: true

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'
